# Generated by Django 4.1.6 on 2023-02-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='quantité',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
