# Generated by Django 4.1.6 on 2023-02-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_article_quantité'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='quantité',
            field=models.CharField(max_length=50),
        ),
    ]
