# Generated by Django 4.1.6 on 2023-02-14 14:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0009_alter_article_quantité'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_p', models.CharField(max_length=50)),
                ('description_p', models.TextField()),
                ('image_p', models.ImageField(blank=True, null=True, upload_to='media')),
                ('quantité_p', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('category_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.category')),
                ('user_p', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
