# Generated by Django 4.1.6 on 2023-02-14 15:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_alter_panier_category_p_alter_panier_description_p_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='category_p',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='description_p',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='image_p',
        ),
        migrations.CreateModel(
            name='Articles_panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_a', models.CharField(max_length=50, null=True)),
                ('description_a', models.TextField(null=True)),
                ('image_a', models.ImageField(blank=True, null=True, upload_to='media')),
                ('quantité_a', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('category_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.category')),
            ],
        ),
    ]
