# Generated by Django 4.1.6 on 2023-02-14 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_remove_panier_category_p_remove_panier_description_p_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='user_p',
        ),
        migrations.DeleteModel(
            name='Articles_panier',
        ),
        migrations.DeleteModel(
            name='Panier',
        ),
    ]
