# Generated by Django 4.1.6 on 2023-02-14 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_alter_panier_achat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='user',
        ),
    ]
