# Generated by Django 4.1.6 on 2023-02-14 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0019_article_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='achat',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='acheté_p',
        ),
        migrations.AddField(
            model_name='panier',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.article'),
        ),
        migrations.AddField(
            model_name='panier',
            name='quantité_panier',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Achat',
        ),
    ]
