# Generated by Django 4.1.6 on 2023-02-14 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0021_remove_panier_article_remove_panier_quantité_panier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='achat',
        ),
        migrations.AddField(
            model_name='achat',
            name='panier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.panier'),
        ),
        migrations.AddField(
            model_name='panier',
            name='achats',
            field=models.ManyToManyField(related_name='paniers', to='gestion.achat'),
        ),
    ]
