# Generated by Django 4.1.6 on 2023-02-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0022_remove_panier_achat_achat_panier_panier_achats'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
